### ISSUE TITLE
Collapsing Lens

### ISSUE THREAD

**Issue by joofio** [Gravitate-Health/mvp-issues#8]
`As a user, I want sections of the ePI collapsed so that they are hidden from me.`

Meaning: Create a lens that collapses data, or greys out. But not remove content

**Comment by amedranogil** [comment]
I would not say there is a single collapsing lens, each lens has the capability of highlighting and collapsing content, because each lens already contians the content for highlighting, it should not be far fetched to assume they would also be able to include collapsing in their areas of expertise.
I woudl recommend renaming this issue to "Collapse functionality for lenses"

**Comment by joofio** [comment]
feedback meeting 5/12: we need to take into account is to collapse only sections. We need to show the mockups and decide if collapse or greyout or other. Then we an example of a lens to develop that lens.

**Comment by gmej** [comment]
We have created an issue in the correct repository : [focusing-manager/27](https://github.com/Gravitate-Health/focusing-manager/issues/27)

**Comment by joofio** [comment]
> We have created an issue in the correct repository : [focusing-manager/27](https://github.com/Gravitate-Health/focusing-manager/issues/27)

why not transfer? better no?

**Comment by aalonsolopez** [comment]
Can we close this for being duplicated?

**Comment by joofio** [comment]
yes
